name: CI - Build & Test Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installer JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build Maven
        run: mvn -B package
        working-directory: ./backend

      - name: Exécuter les tests
        run: mvn test
        working-directory: ./backend

      - name: Construire l'image Docker
        run: docker build -t tp4-backend .
        working-directory: ./backend
